language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

env:
  - REQUESTS_VERSION=1.0.0
  - REQUESTS_VERSION=1.2.3

install:
  - "pip install pytest-cov coveralls"
  - "pip install ."
  - "pip install requests==$REQUESTS_VERSION"

script:
  py.test --runslow --cov tweetstream

after_success:
  coveralls
