language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - pypy

install:
  - "pip install ."
  - "pip install pytest-cov coveralls"

script:
  py.test --runslow --cov tweetstream

after_success:
  coveralls
